### ISSUE TITLE
Подготовка nodemailer к работе с формами

### ISSUE THREAD

**Issue by Govard9** [Team-Code-Wizards/frontend#150]
- [x]  - подготовить к отправке данных форм  ( с вложением и без )
- [x]  - протестировать , SMTP gmail 
- [x]  - протестировать , послать  тестовое письмо себе на почту
- [x]  - внедрить всплытие окна с ошибкой 

- [x] - доп. сделать шаблон письма

**Comment by JackKerouac1613** [comment]
Взял
