### ISSUE TITLE
Настроить форму с модального окна Заявки

### ISSUE THREAD

**Issue by Govard9** [Team-Code-Wizards/frontend#152]
![Image](https://github.com/Team-Code-Wizards/frontend/assets/114614095/c7eff21b-d70b-4454-b606-0f136f45dc12)

- [x]  - логика открытия попапа
- [x]  - открытия дропдаун меню
- [x]  - используем react-hook-form 
- [x]  - настройка валидации
- [x]  - подготовка обьекта к отправке
- [x]  - кнопка сабмитер должна быть заблокирована

**Comment by EkaterinaYurchyk2022** [comment]
Взяла
