### ISSUE TITLE
Настройка попапов "Успешная отправка" и "Инфо-попап" и бургер-меню

### ISSUE THREAD

**Issue by Govard9** [Team-Code-Wizards/frontend#153]
![Image](https://github.com/Team-Code-Wizards/frontend/assets/114614095/77583830-9a59-4155-9b57-3b4ba2fe5215)

- [x] - добавить контент в карточки блока "Услуги"
- [x] - открытие соответствующего попапа при клике на знак вопроса в блоке "Услуги"
- [x] - закрытие попапа при клике на закрыть
- [x] - открытие попапа "Заявки" при клике на кнопку заказать 
**
![Image](https://github.com/Team-Code-Wizards/frontend/assets/114614095/60475be7-8b31-475a-844c-71ba6b85fa11)

- [x]  - логика открытия / закрытия
- [x]  - передать разработчику который работает по задаче с nodemailer

**
![Image](https://github.com/Team-Code-Wizards/frontend/assets/114614095/a71b5ac1-2696-43bc-801d-2307d10464a5)

- [x]  настроить логику открытия/закрытия бургер меню
- [x]  клик по иконке телефона при бургер меню должен отрабатывать как клик по номеру телефона на десктопе

**Comment by natanchik** [comment]
Взяла
