### ISSUE TITLE
Настроить логику блока "Этапы создания"

### ISSUE THREAD

**Issue by Govard9** [Team-Code-Wizards/frontend#155]
![Image](https://github.com/Team-Code-Wizards/frontend/assets/114614095/2577587c-5c6e-4852-9b95-a8b4afd1de01)

Без использования слайдера

- [x] проработать логику смены этапов 
- [x] клик по кнопке Следующий переводит к след шагу
- [x]  клик по кружочку с номером шага переводит к этому шагу 

- [x] доп.  предложить варианты анимации

**
![Image](https://github.com/Team-Code-Wizards/frontend/assets/114614095/fe474d22-0711-4641-8e23-a0e5a7aa98f3)

- [x]  при открытии одной подсказки остальные должны быть закрыты 
- [x] пофиксить баг " при открытии подсказки title становиться в 4 строки"
- [ ]  предложить варианты анимации

**Comment by darikomarenko** [comment]
Взяла
