### ISSUE TITLE
Реализовать фичу динамическая валюта

### ISSUE THREAD

**Issue by OGSmit** [Team-Code-Wizards/frontend#167]
![Image](https://github.com/Team-Code-Wizards/frontend/assets/114614095/bd023ef0-0b8d-4cfa-be92-673337292dfe)

- [ ] - [ ]  - зависимости от региона показывать нужную валюту ( из России показываем цену в рублях , остальное доллары ) в блоке "Услуги"

**Comment by darikomarenko** [comment]
Взяла, пробую делать через IP
