### ISSUE TITLE
Баг-репорты в "Отзывы и рекомендации"

### ISSUE THREAD

**Issue by Govard9** [Team-Code-Wizards/frontend#191]
- [x] Залить видео отзывы, чтобы поддерживали кодеки в сафари. Добавить формат в IOS. (Сделает Влад)
- [x] Недоступно видео читсый город в разделе отзывы и рекомендации в браузере Safari. (Как Влад зальёт, то нужно проверить на сафари)
- [x] В разделе Отзывы и рекомендации название видео Василек написано с буквой ё. - [x]
- [x] В разделе Этапы создания сайта название этапа Верстка написано с буквой ё. - [x]
- [x] Добавить брекпоинт на размер 844px, в "Отзывы" и на этом размере поправить NAV меню. - [x]
- [x] В разделе Отзывы и рекомендации картинка под видео Василек отличается. - [x]

**Comment by JackKerouac1613** [comment]
Взял
