### ISSUE TITLE
Анимация блока "Почему нас выбирают"

### ISSUE THREAD

**Issue by Govard9** [Team-Code-Wizards/frontend#202]
![Image](https://github.com/Team-Code-Wizards/frontend/assets/63837534/ac0fa161-82b3-468f-a96a-783bde581151)

Ссылка на анимацию: https://jitter.video/file/?id=k6PIgc0CKpAxWXVOci8mnMBA&utm_source=share_button

**Comment by JackKerouac1613** [comment]
Взял
