### ISSUE TITLE
Анимация блока "Взаимодействие с нами"

### ISSUE THREAD

**Issue by Govard9** [Team-Code-Wizards/frontend#203]
![Image](https://github.com/Team-Code-Wizards/frontend/assets/63837534/c3041b96-6c25-4454-af68-2ffba0b1bb1c)

Ссылка на анимацию: https://jitter.video/file/?id=99iToaIH5X1AtoR1VIRgV0ie&utm_source=share_button

**Comment by EkaterinaYurchyk2022** [comment]
Взяла
