### ISSUE TITLE
В анимации блока "почему нас выбирают" при обновлении страницы первым появляется слайд - "уникальный дизайн" вместо "онлайн присутствие"

### ISSUE THREAD

**Issue by EkaterinaMarkin** [Team-Code-Wizards/frontend#290]
Предусловие: 701рх

Шаги:
1 Открыть https://code-wizards.team/#portfolio
2 Проскроллить до блока "почему нас выбирают"

ФР: анимация снизу вверх, первый слайдер стоит: "уникальный дизайн" 
ОР: анимация сверху вниз

![Image](https://github.com/Team-Code-Wizards/frontend/assets/161009266/ea50b62d-1d40-4dcb-abd6-91784be45df1)

, первый слайдер стоит: "онлайн присутствие"

**Comment by JackKerouac1613** [comment]
Взял
