### ISSUE TITLE
background в блоке "почему нас выбирают" длиннее самих заголовков

### ISSUE THREAD

**Issue by EkaterinaMarkin** [Team-Code-Wizards/frontend#293]
Шаги:
1 Открыть https://code-wizards.team/#portfolio
2 Проскроллить до блока "почему нас выбирают"

ФР: background длиннее заголовков
ОР: background равен заголовку (см приложение)

![Image](https://github.com/Team-Code-Wizards/frontend/assets/161009266/e1e4c948-344f-4374-8d73-eb025fe612dd)

![Image](https://github.com/Team-Code-Wizards/frontend/assets/161009266/01a6787b-6b27-4e7b-bc18-b2304477c6ad)
![Image](https://github.com/Team-Code-Wizards/frontend/assets/161009266/152644ba-1b67-4dc1-b55d-8be27bdbf826)
![Image](https://github.com/Team-Code-Wizards/frontend/assets/161009266/db76847d-1f45-40d9-b3d9-7c8db3417862)

Комментарий: отображается почти на всех разрешениях

**Comment by JackKerouac1613** [comment]
Взял
